networks:
  calculator:
    driver: bridge
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - calculator
    volumes:
      - redis_data:/data/db
  node:
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    build: ./
    ports:
      - 5000:5000
    networks:
      - calculator
    volumes:
      - node_data:/app/data
    depends_on:
      - redis
volumes:
  redis_data:
  node_data: